title: Cristhian Fuentes
description: Notas, ideas y proyectos.
url: "https://casafuego.github.io"
baseurl: ""

author:
  name: Cristhian Fuentes

twitter:
  username: casafuego

logo: /assets/img/og-default.png
permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: /temas/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - setup-jekyll.sh
