title: Cristhian Fuentes
description: Notas, ideas y proyectos.
url: ""
baseurl: ""
permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: /temas/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - setup-jekyll.sh
